apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: spring-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: jhonoquendo/spring-boot-sonarqube
